/*
 * This source file was generated by the Gradle 'init' task
 */
package pvz;

import java.util.Scanner;

// import pvz.plantfactory.*;
// import pvz.plant.*;
// import pvz.zombiefactory.*;
// import pvz.zombie.*;
import pvz.menu.*;
import pvz.pack.Inventory;

public class App {
    public static void banner() {
        System.out.println("Welcome to Michael vs. Lalapan!");
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        banner();

        Inventory inventory;
        inventory = new Inventory();

        System.out.println(inventory.getPack().size());
        inventory.printInfo();

        inventory.swap(1, 2);
        inventory.printInfo();


        try {
            inventory.swap(1, 3);
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }

        // System.out.println("Choose a command:");
        // System.out.println("1. Start");
        // System.out.println("2. Help");
        // System.out.println("3. Plants List");
        // System.out.println("4. Zombies List");
        // System.out.println("5. Exit");
        // System.out.print("Input [1..5]: ");
        // int command = scanner.nextInt();

        // if (command == 1) {
        //     Menu start = new Start();
        //     start.select();
        // } 
        // else if (command == 2) {
        //     Menu help = new Help();
        //     help.select();
        // } 
        // else if (command == 3) {
        //     Menu plantsList = new PlantsList();
        //     plantsList.select();
        // } 
        // else if (command == 4) {
        //     Menu zombiesList = new ZombiesList();
        //     zombiesList.select();
        // } 
        // else if (command == 5) {
        //     Menu exit = new Exit();
        //     exit.select();
        // }

        

        scanner.close();
    }
}
