/*
 * This source file was generated by the Gradle 'init' task
 */
package pvz;

import java.util.Scanner;

import pvz.menu.Help;
import pvz.menu.PlantsList;
import pvz.menu.ZombiesList;
import pvz.plant.*;
import pvz.plantfactory.*;
import pvz.zombiefactory.*;
import pvz.zombie.*;

public class App {
    public static void banner() {
        System.out.println("Welcome to Michael vs. Lalapan!");
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        PlantsList plantsList = new PlantsList();
        Help help = new Help();
        ZombiesList ZomList = new ZombiesList();
        boolean exit = false;

        banner();
        System.out.println("Silahkan Tekan Tombol dibawah ini");
        System.out.println("1. Start");
        System.out.println("2. Help");
        System.out.println("3. List Plan");
        System.out.println("4. List Zombie");
        System.out.println("5. Exit");
        while (!exit) {
            String x = scanner.nextLine();
            if (x.equals("Start")) {
                System.out.println("Implementasi Tanaman Michael ");
                PlantFactory peashooterFactory = new PeashooterFactory();
                Plant peashooter = peashooterFactory.createPlant();

                PlantFactory wallnutFactory = new WallnutFactory();
                Plant wallnut = wallnutFactory.createPlant();

                PlantFactory ChomperFactory = new ChomperFactory();
                Plant chomper = ChomperFactory.createPlant();

                PlantFactory SunflowerFactory = new SunflowerFactory();
                Plant sunflow = SunflowerFactory.createPlant();

                PlantFactory snowPlantFactory = new SnowpeaFactory();
                Plant snow = snowPlantFactory.createPlant();

                peashooter.printInfo();
                System.out.println();
                wallnut.printInfo();
                System.out.println();
                chomper.printInfo();
                System.out.println();
                sunflow.printInfo();
                System.out.println();
                snow.printInfo();
                System.out.println();

                System.out.println("Implementasi Zombie");
                ZombieFactory normalFactory = new NormalFactory();
                Zombie normal = normalFactory.createZombie();

                ZombieFactory poleVaultFactory = new PoleVaultFactory();
                Zombie poleVault = poleVaultFactory.createZombie();

                normal.printInfo();
                System.out.println();
                poleVault.printInfo();
                System.out.println();
            } else if (x.equals("Help")) {
                help.select();
                System.out.println("Silahkan pilih menu yang diinginkan : ");
            } else if (x.equals("List Plan")) {
                plantsList.select();
            } else if (x.equals("List Zombie")) {
                ZomList.select();
            } else if (x.equals("Exit")) {
                exit = true;
            } else {
                System.out.println("Masukkan Tombol yang tepat");
            }
        }

        scanner.close();
    }
}
