// /*
//  * This source file was generated by the Gradle 'init' task
//  */
// package pvz;

// import java.util.Scanner;

// import pvz.main.Help;
// import pvz.main.PlantsList;
// import pvz.map.Map;
// // import pvz.main.ZombiesList;
// import pvz.plant.*;
// import pvz.plantfactory.*;
// import pvz.zombiefactory.*;
// import pvz.zombie.*;

// public class AppMap {
//     public static void banner() {
//         System.out.println("Welcome to Michael vs. Lalapan!");
//     }

//     public static void main(String[] args) {
//         Scanner scanner = new Scanner(System.in);
//         PlantsList plantsList = new PlantsList();
//         Help help = new Help();
//         // ZombiesList ZomList = new ZombiesList();
//         boolean exit = false;
//         PlantFactory snowPlantFactory = new SnowpeaFactory();
//         Plant snow = snowPlantFactory.createPlant(0);
//         LilypadFactory Lyli = new LilypadFactory();
//         Plant pad = Lyli.createPlant(0);

//         banner();
//         System.out.println("Silahkan Tekan Tombol dibawah ini");
//         System.out.println("1. Start");
//         System.out.println("2. Help");
//         System.out.println("3. List Plan");
//         System.out.println("4. List Zombie");
//         System.out.println("5. Exit");
//         while (!exit) {
//             String x = scanner.nextLine();
//             if (x.equals("Start")) {
//                 System.out.println("Implementasi Tanaman Michael ");
//                 PlantFactory peashooterFactory = new PeashooterFactory();
//                 Plant peashooter = peashooterFactory.createPlant(0);

//                 PlantFactory wallnutFactory = new WallnutFactory();
//                 Plant wallnut = wallnutFactory.createPlant(0);

//                 PlantFactory ChomperFactory = new ChomperFactory();
//                 Plant chomper = ChomperFactory.createPlant(0);

//                 PlantFactory SunflowerFactory = new SunflowerFactory();
//                 Plant sunflow = SunflowerFactory.createPlant(0);

//                 peashooter.printInfo();
//                 System.out.println();
//                 wallnut.printInfo();
//                 System.out.println();
//                 chomper.printInfo();
//                 System.out.println();
//                 sunflow.printInfo();
//                 System.out.println();
//                 snow.printInfo();
//                 System.out.println();

//                 System.out.println("Implementasi Zombie");
//                 ZombieFactory normalFactory = new NormalFactory();
//                 Zombie normal = normalFactory.createZombie();

//                 ZombieFactory poleVaultFactory = new PoleVaultFactory();
//                 Zombie poleVault = poleVaultFactory.createZombie();

//                 normal.printInfo();
//                 System.out.println();
//                 poleVault.printInfo();
//                 System.out.println();
//             } else if (x.equals("Help")) {
//                 help.select();
//                 System.out.println("Silahkan pilih menu yang diinginkan : ");
//             } else if (x.equals("List Plan")) {
//                 plantsList.select();
//             } else if (x.equals("List Zombie")) {
//                 Map map = new Map();
//                 map.displayMap();
//                 map.plant(1, 1, snow);
//                 map.plant(3, 1, pad);
//                 map.displayMap();
//             } else if (x.equals("Exit")) {
//                 exit = true;
//             } else {
//                 System.out.println("Masukkan Tombol yang tepat");
//             }
//         }

//         scanner.close();
//     }
// }